HUMANAPI_CLIENT_ID: ""
HUMANAPI_CLIENT_SECRET: ""
FITBIT_KEY: ""
FITBIT_SECRET: ""
WITHINGS_KEY: ""
WITHINGS_SECRET: ""
INTERCOM_APP_ID: ""
INTERCOM_APP_API_KEY: ""
FACTUAL_KEY: ""
FACTUAL_SECRET: ""
GITHUB_KEY: ""
GITHUB_SECRET: ""
STRIPE_SECRET_KEY: ""
STRIPE_PUBLISHABLE_KEY: ""
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
AWS_REGION: ''
CLOUD66_BEARER: ""

development:
  APNS_CERTIFICATE_PATH: ""
  HUMANAPI_APP_KEY: ""
  MOVES_KEY: ""
  MOVES_SECRET: ""
  INTERCOM_APP_ID: ""
  INTERCOM_APP_API_KEY: ""
  STRIPE_SECRET_KEY: ""
  STRIPE_PUBLISHABLE_KEY: ""

test:
  APNS_CERTIFICATE_PATH: ""
  HUMANAPI_APP_KEY: ""
  PUSHER_APP_ID: ""
  PUSHER_KEY: ""
  PUSHER_SECRET: ""
  FACTUAL_KEY: ""
  FACTUAL_SECRET: ""
  STRIPE_SECRET_KEY: ""
  STRIPE_PUBLISHABLE_KEY: ""
